#
# Build and push PostHog and PostHog Cloud container images
#
# - posthog_build: build and push the PostHog container image to DockerHub
#
# - posthog_cloud_build: build the PostHog Cloud container image using
#   as base image the container image from the previous step. The image is
#   then pushed to AWS ECR.
#
name: Container Images CD

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'rust/**'
            - 'livestream/**'
    workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write
  packages: write

env:
  GAR_REGISTRY: us-central1-docker.pkg.dev/follow-428106/follow

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - name: posthog
            context: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/987979088361/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: gh-action@naturalselectionlabs.iam.gserviceaccount.com
          create_credentials_file: true

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GAR_REGISTRY }}/${{ matrix.images.name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=sha,format=long
            type=sha,prefix={{branch}}-,enable=${{ !startsWith(github.ref, 'refs/tags') }},event=branch
            type=sha,format=long,prefix={{branch}}-,enable=${{ !startsWith(github.ref, 'refs/tags') }},event=branch

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.images.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}